[2024-02-16T23:21:17.960+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper scheduled__2024-02-15T23:21:00.101751+00:00 [queued]>
[2024-02-16T23:21:18.065+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper scheduled__2024-02-15T23:21:00.101751+00:00 [queued]>
[2024-02-16T23:21:18.067+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T23:21:18.254+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_2_copy_mapper> on 2024-02-15 23:21:00.101751+00:00
[2024-02-16T23:21:18.263+0000] {standard_task_runner.py:60} INFO - Started process 1265 to run task
[2024-02-16T23:21:18.272+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline_FINAL', 'step_2_copy_mapper', 'scheduled__2024-02-15T23:21:00.101751+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmpbzathf1u']
[2024-02-16T23:21:18.276+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask step_2_copy_mapper
[2024-02-16T23:21:18.509+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline_FINAL.step_2_copy_mapper scheduled__2024-02-15T23:21:00.101751+00:00 [running]> on host a1bb76e936e6
[2024-02-16T23:21:18.779+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline_FINAL' AIRFLOW_CTX_TASK_ID='step_2_copy_mapper' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T23:21:00.101751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T23:21:00.101751+00:00'
[2024-02-16T23:21:18.810+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -put C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\mapper.py /python' returned non-zero exit status 127.
[2024-02-16T23:21:18.811+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T23:21:18.838+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline_FINAL, task_id=step_2_copy_mapper, execution_date=20240215T232100, start_date=20240216T232117, end_date=20240216T232118
[2024-02-16T23:21:18.929+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T23:21:18.994+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
