[2024-02-16T23:21:05.253+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_1_load_data scheduled__2024-02-15T23:20:58.966802+00:00 [queued]>
[2024-02-16T23:21:05.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HADOOP_ELT_pipeline_FINAL.step_1_load_data scheduled__2024-02-15T23:20:58.966802+00:00 [queued]>
[2024-02-16T23:21:05.278+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-16T23:21:05.340+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): step_1_load_data> on 2024-02-15 23:20:58.966802+00:00
[2024-02-16T23:21:05.350+0000] {standard_task_runner.py:60} INFO - Started process 1231 to run task
[2024-02-16T23:21:05.354+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'HADOOP_ELT_pipeline_FINAL', 'step_1_load_data', 'scheduled__2024-02-15T23:20:58.966802+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ELT_automated_airflow.py', '--cfg-path', '/tmp/tmpbsd228pb']
[2024-02-16T23:21:05.358+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask step_1_load_data
[2024-02-16T23:21:05.515+0000] {task_command.py:423} INFO - Running <TaskInstance: HADOOP_ELT_pipeline_FINAL.step_1_load_data scheduled__2024-02-15T23:20:58.966802+00:00 [running]> on host a1bb76e936e6
[2024-02-16T23:21:05.806+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='HADOOP_ELT_pipeline_FINAL' AIRFLOW_CTX_TASK_ID='step_1_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T23:20:58.966802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-15T23:20:58.966802+00:00'
[2024-02-16T23:21:05.837+0000] {logging_mixin.py:188} INFO - Error occurred: Command 'hadoop fs -copyFromLocal C:\Users\LENOVO\ETL-and-ELT-integration-pipelines\sales_csv /sales_data' returned non-zero exit status 127.
[2024-02-16T23:21:05.838+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-16T23:21:05.864+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=HADOOP_ELT_pipeline_FINAL, task_id=step_1_load_data, execution_date=20240215T232058, start_date=20240216T232105, end_date=20240216T232105
[2024-02-16T23:21:05.976+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-16T23:21:06.064+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
